ZemaxFringeTerms = table( ...
    (1:20).', ...
    { ...
        'Piston'; ...
        'Tilt X'; ...
        'Tilt Y'; ...
        'Defocus'; ...
        'Astigmatism 45°'; ...
        'Astigmatism 0°'; ...
        'Coma Y'; ...
        'Coma X'; ...
        'Trefoil Y'; ...
        'Trefoil X'; ...
        'Primary Spherical'; ...
        'Secondary Astigmatism 45°'; ...
        'Secondary Astigmatism 0°'; ...
        'Quadrafoil Y'; ...
        'Quadrafoil X'; ...
        'Secondary Coma Y'; ...
        'Secondary Coma X'; ...
        'Secondary Trefoil Y'; ...
        'Secondary Trefoil X'; ...
        'Pentafoil Y' ...
    }, ...
    { ...
        '1'; ...
        'ρ cosθ'; ...
        'ρ sinθ'; ...
        '2ρ² − 1'; ...
        'ρ² sin(2θ)'; ...
        'ρ² cos(2θ)'; ...
        '(3ρ³ − 2ρ) sinθ'; ...
        '(3ρ³ − 2ρ) cosθ'; ...
        'ρ³ sin(3θ)'; ...
        'ρ³ cos(3θ)'; ...
        '6ρ⁴ − 6ρ² + 1'; ...
        '(4ρ⁴ − 3ρ²) sin(2θ)'; ...
        '(4ρ⁴ − 3ρ²) cos(2θ)'; ...
        'ρ⁴ sin(4θ)'; ...
        'ρ⁴ cos(4θ)'; ...
        '(10ρ⁵ − 12ρ³ + 3ρ) sinθ'; ...
        '(10ρ⁵ − 12ρ³ + 3ρ) cosθ'; ...
        '(5ρ⁵ − 4ρ³) sin(3θ)'; ...
        '(5ρ⁵ − 4ρ³) cos(3θ)'; ...
        'ρ⁵ sin(5θ)' ...
    }, ...
    'VariableNames', {'#','Name','Formula'} ...
);