function out1 = A1_func(P)
%A1_func
%    OUT1 = A1_func(P)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Sep-2024 12:00:50

t2 = -P;
out1 = [0.0,t2,0.0,0.0,0.0,0.0,t2];
end
