function A3 = A3_func(R)
%A3_func
%    A3 = A3_func(R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Sep-2024 12:00:50

t2 = -R;
A3 = reshape([0.0,R,0.0,0.0,0.0,R,0.0,R,t2,0.0,t2,0.0,0.0,0.0],[2,7]);
end
