function A4 = A4_func(theta_dot)
%A4_func
%    A4 = A4_func(THETA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Sep-2024 12:00:50

t2 = -theta_dot;
A4 = reshape([0.0,0.0,0.0,0.0,0.0,t2,0.0,t2,0.0,0.0,0.0,0.0,theta_dot,0.0],[2,7]);
end
