function A5 = A5_func(psi_dot)
%A5_func
%    A5 = A5_func(PSI_DOT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Sep-2024 12:00:50

A5 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,psi_dot,-psi_dot,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
