function A_IK_reduced = A_IK(c_psi,c_theta,eg1,eg2,eia1,eoa1,eoa3,psi_o,s_psi,s_theta,theta_o)
%A_IK
%    A_IK_reduced = A_IK(C_PSI,C_THETA,EG1,EG2,EIA1,EOA1,EOA3,PSI_O,S_PSI,S_THETA,THETA_O)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    28-Sep-2024 18:21:52

t2 = 1.0./c_psi;
t3 = t2.^2;
A_IK_reduced = reshape([eoa3-eia1.*s_theta+c_theta.*psi_o.*t3+c_theta.*s_psi.*t2-s_psi.*s_theta.*t2.*theta_o,-s_theta-c_theta.*theta_o-c_theta.*eg2.*t2+c_theta.*eia1.*s_psi.*t2,c_theta.*eoa3.*s_psi.*t2+eoa1.*s_psi.*s_theta.*t2-1.0,c_theta.*eoa1-eoa3.*s_theta,-eoa1-c_theta.*eia1-psi_o.*s_theta.*t3-s_psi.*s_theta.*t2-c_theta.*s_psi.*t2.*theta_o,-c_theta+s_theta.*theta_o+eg2.*s_theta.*t2-eia1.*s_psi.*s_theta.*t2,t2+psi_o.*s_psi.*t3,eg1+eia1.*t2-eg2.*s_psi.*t2,-eg1.*t2,1.0],[2,5]);
end
