function Argon_NIST_sat = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARGON_NIST_SAT = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ARGON_NIST_SAT = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Argon_NIST_sat = importfile("D:\Git\Vision\EXPC\Argon_NIST_sat.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Jan-2026 18:59:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TemperatureK", "PressureMPa", "Density_l_Kgm3", "Volume_l_M3kg", "InternalEnergy_l_KJkg", "Enthalpy_l_KJkg", "Entropy_l_JgK", "Cv_l_JgK_", "Cp_l_JgK", "SoundSpd_l_Ms", "JouleThomson_l_KMPa", "Viscosity_l_Pas", "ThermCond_l_WmK", "Surf_Tension_l_Nm", "Density_v_Kgm3", "Volume_v_M3kg", "InternalEnergy_v_KJkg", "Enthalpy_v_KJkg", "Entropy_v_JgK", "Cv_v_JgK", "Cp_v_JgK", "SoundSpd_v_Ms", "JouleThomson_v_KMPa", "Viscosity_v_Pas", "Therm_Cond__v_WmK"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "skip";

% Import the data
Argon_NIST_sat = readtable(filename, opts);

end