function Argon_NIST = Nist_Table_Loader(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARGON_NIST = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ARGON_NIST = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Argon_NIST = importfile("D:\Git\Vision\EXPC\Argon_NIST.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Feb-2026 17:04:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TemperatureK", "PressureMPa", "Densitykgm3", "Volumem3kg", "InternalEnergykJkg", "EnthalpykJkg", "EntropyJgK", "CvJgK", "CpJgK", "SoundSpdms", "JouleThomsonKMPa", "ViscosityPas", "ThermCondWmK", "Phase"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "skip";

% Specify variable properties
opts = setvaropts(opts, "Phase", "EmptyFieldRule", "auto");

% Import the data
Argon_NIST = readtable(filename, opts);

end